version: '3'

services:
  postgres:
    image: postgres:latest
    networks:
      - postgres-db
    ports:
      - "5432:5432"
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: matboj

  matboj:
    build: .
    image: lukasanda/matboj:1.0.0
    networks:
      - postgres-db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    hostname: springdemo
    container_name: matboj
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/matboj
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres1234

networks:
  postgres-db:
    driver: bridge

volumes:
  data: {}
